### ISSUE TITLE
lief.COFF.Binary missing `format` attribute (and probably other attributes expected from other Binary classes)

### ISSUE THREAD

**Issue by insolor** [lief-project/LIEF#1292]
**Describe the bug**
`lief.COFF.Binary` missing `format` attribute.

**To Reproduce**

```python
import lief

parsed = lief.parse("coff.obj")
if not parsed:
    print("Couldn't parse the file")
else:
    print(f"File format is {parsed.format}")
```

Error:
```
    print(f"File format is {parsed.format}")
                            ^^^^^^^^^^^^^
AttributeError: 'lief._lief.COFF.Binary' object has no attribute 'format'
```

Such code will break on COFF files and work on other formats.

Even if I don't intend parse COFF, I have a problem with mypy after updating lief to 0.17+. For example, I had a previously valid code:

```python
import lief

parsed_binary = lief.parse("unknown.bin")

if parsed_binary:
    print(f"Detected file format: {parsed_binary.format}")

    if isinstance(parsed_binary, lief.PE.Binary):
        # Some code specific for PE
        pass
    elif isinstance(parsed_binary, lief.ELF.Binary):
        # Some code specific for ELF
        pass
    else:
        msg = f"Unsupported file format: {parsed_binary.format}"
        raise TypeError(msg)

    ...
```

mypy (mypy 1.19.1) will now report several problems:

```
> uv run mypy broken_code.py --strict
broken_code.py:6: error: Item "lief.COFF.Binary" of "lief.PE.Binary | lief.ELF.Binary | lief.MachO.Binary | lief.COFF.Binary" has no attribute "format"  [union-attr]
broken_code.py:15: error: Item "lief.COFF.Binary" of "lief.MachO.Binary | lief.COFF.Binary" has no attribute "format"  [union-attr]
Found 2 errors in 1 file (checked 1 source file)
```

As a workaround, I print the file format if is PE or ELF and just don't report format in case it is not supported ([commit](https://github.com/dfint/search_offsets/commit/f864d6043b8f8c6f3020bb0757f2f5c3a9bec5ba)).

**Expected behavior**
In general, I expect that the new `lief.COFF.Binary` conform with the "protocol" common for other `Binary` classes. At minimum, I expect that `lief.COFF.Binary` has `.format` attribute.

**Environment:**
 - System and Version : Linux Mint 22.3
 - Target format : COFF, PE, ELF
 - LIEF commit version: 0.17.3-03aca30b
