### PR TITLE
fix aarch64 library name #901

### LINKED ISSUE #901: "import lief" not work on 0.13.0
**Describe the bug**

```
>>> import lief
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/lief/__init__.py", line 2, in <module>
    from . import _lief
ImportError: cannot import name '_lief' from partially initialized module 'lief' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/lief/__init__.py)
>>>
```

**To Reproduce**
`pip3 install lief==0.13.0`
`python3 -c "import lief"`

**Expected behavior**
like lief 0.12.3 works:
```
rock@rock-5b:~$ python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
>>> lief
<module 'lief' from '/usr/local/lib/python3.8/dist-packages/lief.cpython-38-aarch64-linux-gnu.so'>
```

**Environment (please complete the following information):**
```
 rock@rock-5b:~$ sudo pip3 uninstall lief
Found existing installation: lief 0.13.0
Uninstalling lief-0.13.0:
  Would remove:
    /usr/local/bin/elf_reader.py
    /usr/local/bin/macho_reader.py
    /usr/local/bin/pe_reader.py
    /usr/local/lib/python3.8/dist-packages/lief-0.13.0.dist-info/*
    /usr/local/lib/python3.8/dist-packages/lief/*
Proceed (y/n)? y
  Successfully uninstalled lief-0.13.0
rock@rock-5b:~$ sudo pip3 install lief
Collecting lief
  Using cached lief-0.13.0-cp38-cp38-manylinux2014_aarch64.whl (4.2 MB)
Installing collected packages: lief
Successfully installed lief-0.13.0
```
```
rock@rock-5b:~$ neofetch
            .-/+oossssoo+/-.               rock@rock-5b
        `:+ssssssssssssssssss+:`           ------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04 LTS aarch64
    .ossssssssssssssssssdMMMNysssso.       Host: Radxa ROCK 5B
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.10.110-99-rockchip-gf1011079b3c0
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 8 hours, 34 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1139 (dpkg)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.16
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: /dev/pts/40
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: (8) @ 1.800GHz
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Memory: 1426MiB / 15721MiB
+sssshhhyNMMNyssssssssssssyNMMMysssssss+
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```
**Additional context**
```
rock@rock-5b:~$ pip3 list |grep lief
lief                0.13.0
```

### PR DESCRIPTION
**Pull request by DiamondHunters**
Add less invasive code to correct dst file name by configuring `SETUPTOOLS_EXT_SUFFIX`

Problems and solutions are in #901 

fixed #901

### CODE REVIEW

**Comment by romainthomas** [comment]
Thank you again @DiamondHunters for the PR. 

As you will see, I fixed the issue with a proper env variable in the sh script (``manylinux2014-aarch64.sh``). I choose this solution over a modification in the ``setup.py`` because this is something that should be handled by the cross-compilation environment. Not the build script which works "fine". 

Let me know if you have remarks or question.

**Comment by romainthomas** [comment]
Resolved with https://github.com/lief-project/LIEF/commit/0714d2e7832cb7d28e5cc91b997094f97188a33b
