### ISSUE TITLE
build fails with mbedtls 4.2.0

### ISSUE THREAD

**Issue by apteryks** [lief-project/LIEF#1381]
**Describe the bug**
build fails with mbedtls 4.2.0

**To Reproduce**
Configure with `"-DLIEF_OPT_MBEDTLS_EXTERNAL=ON"`, and build with mbedtls 4.1.0 or newer.

**Expected behavior**
Build should succeed.

**Environment (please complete the following information):**
 - System and Version : Guix System
 - Target format (PE, ELF, Mach-O): N/A
 - LIEF commit version: 1.0.0 tag

**Additional context**

This is what the build failure looks like:
```
/gnu/store/bl3qw29h2582k7hpifm90g508z838swc-gcc-14.3.0/bin/c++ -DFMT_SHARED -DJSON_HAS_CPP_11 -DJSON_NOEXCEPTION -DLIB_LIEF_EXPORTS -DLIEF_EXPORTS -DMBEDTLS_CONFIG_FILE=\"/tmp/guix-build-lief-1.0.0.drv-0/source/config/mbedtls/config.h\" -DMBEDTLS_PK_PARSE_C -DMBEDTLS_X509_USE_C -DSPDLOG_COMPILED_LIB -DSPDLOG_DISABLE_DEFAULT_LOGGER -DSPDLOG_FMT_EXTERNAL -DSPDLOG_FUNCTION="" -DSPDLOG_NO_EXCEPTIONS -DSPDLOG_SHARED_LIB -D_GLIBCXX_USE_CXX11_ABI=1 -I/tmp/guix-build-lief-1.0.0.drv-0/source/include -I/tmp/guix-build-lief-1.0.0.drv-0/source/api/c/include -I/tmp/guix-build-lief-1.0.0.drv-0/build/include -I/tmp/guix-build-lief-1.0.0.drv-0/source/src -I/tmp/guix-build-lief-1.0.0.drv-0/build -isystem /gnu/store/9sfwdapx34fs3lgnnkba4gksb0k95l7j-libexpected-1.3.1/share -isystem /gnu/store/kq767gd22pbcx1sgc1b9qbvyq6n2qiny-utfcpp-4.1.1/include/utf8cpp -O2 -g -DNDEBUG -std=gnu++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -Wall -Wextra -Wpedantic -Wno-expansion-to-defined -Wno-unused-lambda-capture -Werror=return-type -fdiagnostics-color=always -fno-exceptions -Winvalid-pch -include /tmp/guix-build-lief-1.0.0.drv-0/build/CMakeFiles/LIB_LIEF.dir/cmake_pch.hxx -MD -MT CMakeFiles/LIB_LIEF.dir/src/Abstract/json_api.cpp.o -MF CMakeFiles/LIB_LIEF.dir/src/Abstract/json_api.cpp.o.d -o CMakeFiles/LIB_LIEF.dir/src/Abstract/json_api.cpp.o -c /tmp/guix-build-lief-1.0.0.drv-0/source/src/Abstract/json_api.cpp
/tmp/guix-build-lief-1.0.0.drv-0/source/src/visitors/hash.cpp:20:10: fatal error: psa/crypto_builtin_primitives.h: No such file or directory
   20 | #include "psa/crypto_builtin_primitives.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/LIB_LIEF.dir/build.make:291: CMakeFiles/LIB_LIEF.dir/src/visitors/hash.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /tmp/guix-build-lief-1.0.0.drv-0/source/src/BinaryStream/ASN1Reader.cpp:22:
/tmp/guix-build-lief-1.0.0.drv-0/source/src/mbedtls_wraps.h:58:38: error: static assertion failed: Expecting mbedtls 4.0.0
   58 | static_assert(MBEDTLS_VERSION_NUMBER == 0x04000000, "Expecting mbedtls 4.0.0");
      |                                      ^
/tmp/guix-build-lief-1.0.0.drv-0/source/src/mbedtls_wraps.h:58:38: note: the comparison reduces to ‘(67174400 == 67108864)’
In file included from /gnu/store/bn78qgcry82b2bypczy07g8rlinw089h-mbedtls-4.1.0/include/mbedtls/pk.h:15,
                 from /tmp/guix-build-lief-1.0.0.drv-0/source/src/mbedtls_wraps.h:51:
/tmp/guix-build-lief-1.0.0.drv-0/source/src/mbedtls_wraps.h: In function ‘mbedtls_rsa_context* mbedtls_pk_rsa(mbedtls_pk_context)’:
/tmp/guix-build-lief-1.0.0.drv-0/source/src/mbedtls_wraps.h:121:49: error: ‘const mbedtls_pk_context’ {aka ‘const struct mbedtls_pk_context’} has no member named ‘private_pk_ctx’; did you mean ‘private_pk_info’?
  121 |             return (mbedtls_rsa_context *) (pk).MBEDTLS_PRIVATE(pk_ctx);
      |                                                 ^~~~~~~~~~~~~~~
/tmp/guix-build-lief-1.0.0.drv-0/source/src/BinaryStream/BinaryStream.cpp: In member function ‘LIEF::result<long unsigned int> LIEF::BinaryStream::read_sleb128(size_t*) const’:
/tmp/guix-build-lief-1.0.0.drv-0/source/src/BinaryStream/BinaryStream.cpp:138:29: warning: left shift of negative value [-Wshift-negative-value]
  138 |     value |= (int64_t)-1llu << shift;
      |              ~~~~~~~~~~~~~~~^~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unused-lambda-capture’ may have been intended to silence earlier diagnostics
make[2]: *** [CMakeFiles/LIB_LIEF.dir/build.make:339: CMakeFiles/LIB_LIEF.dir/src/BinaryStream/ASN1Reader.cpp.o] Error 1
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unused-lambda-capture’ may have been intended to silence earlier diagnostics
make[2]: Leaving directory '/tmp/guix-build-lief-1.0.0.drv-0/build'
make[1]: *** [CMakeFiles/Makefile2:1104: CMakeFiles/LIB_LIEF.dir/all] Error 2
make[1]: Leaving directory '/tmp/guix-build-lief-1.0.0.drv-0/build'
make: *** [Makefile:159: all] Error 2
```
It builds fine with an external mbedtls at 4.0.0.

**Comment by apteryks** [comment]
mbedtls 4.0.0 also cannot be cross-compiled, a bug resolved in 4.2.0:
```
In file included from /tmp/guix-build-mbedtls-4.0.0.drv-0/mbedtls-4.0.0/tf-psa-crypto/drivers/builtin/src/ctr_drbg.c:13:
In function ‘mbedtls_xor’,
    inlined from ‘ctr_drbg_update_internal’ at /tmp/guix-build-mbedtls-4.0.0.drv-0/mbedtls-4.0.0/tf-psa-crypto/drivers/builtin/src/ctr_drbg.c:373:5:
/tmp/guix-build-mbedtls-4.0.0.drv-0/mbedtls-4.0.0/tf-psa-crypto/core/tf_psa_crypto_common.h:235:17: error: array subscript 48 is outside array bounds of ‘unsigned char[48]’ [-Werror=array-bounds=]
  235 |         r[i] = a[i] ^ b[i];
      |                ~^~~
```
